# Generated by Django 3.0.2 on 2020-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_auto_20200128_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Nombre'),
        ),
    ]
